bookingMovie/config/routes.rb
BookingMovie::Application.routes.draw do
  resources :users

  get "users/login"
  get "payments/make_a_payment"
  get "shopping_carts/add_to_cart"
  get "theatre_movies/theatre_movie_list" 
  resources :theatre_movies
  post "users/login"
  post "payments/make_a_payment"
  post "theatre_movies/theatre_movie_list"
  post "shopping_carts/add_to_cart"
  resources :payments

  resources :reviews

  resources :search_theatres

  get "search_theatres/search_theatre_byzip"
  post "search_theatres/search_theatre_byzip"
  resources :search_thatres

  resources :shopping_carts

  get "main_page/index"
  resources :movies

  resources :shows

  resources :screens

  resources :theatres

end

bookingMovie/app/models/payment.rb
class Payment < ActiveRecord::Base
	belongs_to :shopping_cart
	has_one :user
	validates :credit_card_num, presence: true
	validates :cvv, presence: true
	validates :expiry_date, presence: true
	validates :expiry_date, presence: true
	validates :street_name, presence: true
	validates :city, presence: true
	validates :state, presence: true
	validates :zipcode, presence: true
end

bookingMovie/app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end
  
  def make_a_payment
    @payment = Payment.new
  
  end  
  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment Completed.' }
        format.json { render action: 'show', status: :created, location: @payment }
      else
        format.html { render action: 'new' }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:credit_card_num, :cvv, :expiry_date, :street_name, :city, :state, :zipcode, :amount_paid, :item_id, :user_id)
    end
end

bookingMovie/app/helpers/payments_helper.rb
module PaymentsHelper
end

bookingMovie/app/views/payments/_form.html.erb
<%= form_for(@payment) do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% @payment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :credit_card_num %><br>
    <%= f.text_field :credit_card_num %>
  </div>
  <div class="field">
    <%= f.label :cvv %><br>
    <%= f.number_field :cvv %>
  </div>
  <div class="field">
    <%= f.label :expiry_date %><br>
    <%= f.datetime_select :expiry_date %>
  </div>
  <div class="field">
    <%= f.label :street_name %><br>
    <%= f.text_field :street_name %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zipcode %><br>
    <%= f.text_field :zipcode %>
  </div>
  <div class="field">
    <%= f.label :amount_paid %><br>
    <%= f.text_field :amount_paid %>
  </div>
  <div class="field">
    <%= f.label :item_id %><br>
    <%= f.number_field :item_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

bookingMovie/app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

bookingMovie/app/views/payments/index.html.erb
<h1>Listing payments</h1>

<table>
  <thead>
    <tr>
      <th>Credit card num</th>
      <th>Cvv</th>
      <th>Expiry date</th>
      <th>Street name</th>
      <th>City</th>
      <th>State</th>
      <th>Zipcode</th>
      <th>Amount paid</th>
      <th>Item</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.credit_card_num %></td>
        <td><%= payment.cvv %></td>
        <td><%= payment.expiry_date %></td>
        <td><%= payment.street_name %></td>
        <td><%= payment.city %></td>
        <td><%= payment.state %></td>
        <td><%= payment.zipcode %></td>
        <td><%= payment.amount_paid %></td>
        <td><%= payment.item_id %></td>
        <td><%= payment.user_id %></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

bookingMovie/app/views/payments/make_a_payment.html.erb
<body class = "make_a_payment">

<img class = "image-border">
  <%=image_tag("horizontal-strip.jpg", alt: "Example Image")%>
  
</img>
<div class="left">
      <img class = "image-border-vertical">
        <%=image_tag("vertical-strip.jpg", alt: "Example Image")%>
      </img>
 </div>
<h2><u>Payment Details</u></h2>
<div class="field">
<%= label_tag :name_on_the_card %><br>
<%= text_field_tag :name_on_the_card %>
</div>
<%= form_for(@payment) do |f| %>
  
  <div class="field">
    <%= f.label :credit_card_num %><br>
    <%= f.text_field :credit_card_num %>
  </div>
  <div class="field">
    <%= f.label :cvv %><br>
    <%= f.number_field :cvv %>
  </div>
  <div class="field">
    <%= f.label :expiry_date %><br>
    <%= f.datetime_select :expiry_date, :discard_minute => true, :discard_hour => true %>
  </div>
  <div class="field">
    <%= f.label :street_name %><br>
    <%= f.text_field :street_name %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zipcode %><br>
    <%= f.text_field :zipcode %>
  </div>
  <!-- <div class="field">
    <%= f.label :amount_paid %><br>
    <%= f.text_field :amount_paid %>
  </div>
  <div class="field">
    <%= f.label :item_id %><br>
    <%= f.number_field :item_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div> -->
  <div class="actions">
    <%= f.submit "Make Payment" %>
  </div>
<% end %>
</body>

bookingMovie/app/views/payments/new.html.erb
<h1>New payment</h1>

<%= render 'form' %>

<%= link_to 'Back', payments_path %>

bookingMovie/app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Close this Window</strong>
  
</p>