bookingMovie/config/routes.rb
BookingMovie::Application.routes.draw do
  resources :users

  get "users/login"
  get "payments/make_a_payment"
  get "shopping_carts/add_to_cart"
  get "theatre_movies/theatre_movie_list" 
  resources :theatre_movies
  post "users/login"
  post "payments/make_a_payment"
  post "theatre_movies/theatre_movie_list"
  post "shopping_carts/add_to_cart"
  resources :payments

  resources :reviews

  resources :search_theatres

  get "search_theatres/search_theatre_byzip"
  post "search_theatres/search_theatre_byzip"
  resources :search_thatres

  resources :shopping_carts

  get "main_page/index"
  resources :movies

  resources :shows

  resources :screens

  resources :theatres

end

bookingMovie/app/models/theatre.rb
class Theatre < ActiveRecord::Base
	
	has_many :screens
	has_many :search_theatres
	has_many :theatre_movies
	has_many :movies, through: :theatre_movies
	validates :name, presence: true
	validates :zipcode, presence: true
end

bookingMovie/app/controllers/theatres_controller.rb
class TheatresController < ApplicationController
  before_action :set_theatre, only: [:show, :edit, :update, :destroy]

  # GET /theatres
  # GET /theatres.json
  def index
    @theatres = Theatre.all

  end

  # GET /theatres/1
  # GET /theatres/1.json
  def show
  end

  # GET /theatres/new
  def new
    @theatre = Theatre.new
  end

  # GET /theatres/1/edit
  def edit
  end

  # POST /theatres
  # POST /theatres.json
  def create
    @theatre = Theatre.new(theatre_params)

    respond_to do |format|
      if @theatre.save
        format.html { redirect_to @theatre, notice: 'Theatre was successfully created.' }
        format.json { render action: 'show', status: :created, location: @theatre }
      else
        format.html { render action: 'new' }
        format.json { render json: @theatre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /theatres/1
  # PATCH/PUT /theatres/1.json
  def update
    respond_to do |format|
      if @theatre.update(theatre_params)
        format.html { redirect_to @theatre, notice: 'Theatre was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @theatre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /theatres/1
  # DELETE /theatres/1.json
  def destroy
    @theatre.destroy
    respond_to do |format|
      format.html { redirect_to theatres_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theatre
      @theatre = Theatre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def theatre_params
      params.require(:theatre).permit(:name, :city, :state, :zipcode)
    end
end

bookingMovie/app/helpers/theatres_helper.rb
module TheatresHelper
end

bookingMovie/app/views/theatres/_form.html.erb
<%= form_for(@theatre) do |f| %>
  <% if @theatre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@theatre.errors.count, "error") %> prohibited this theatre from being saved:</h2>

      <ul>
      <% @theatre.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zipcode %><br>
    <%= f.text_field :zipcode %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

bookingMovie/app/views/theatres/edit.html.erb
<h1>Editing theatre</h1>

<%= render 'form' %>

<%= link_to 'Show', @theatre %> |
<%= link_to 'Back', theatres_path %>

bookingMovie/app/views/theatres/index.html.erb
<h1>Listing theatres</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>City</th>
      <th>State</th>
      <th>Zipcode</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @theatres.each do |theatre| %>
      <tr>
        <td><%= theatre.name %></td>
        <td><%= theatre.city %></td>
        <td><%= theatre.state %></td>
        <td><%= theatre.zipcode %></td>
        <td><%= link_to 'Show', theatre %></td>
        <td><%= link_to 'Edit', edit_theatre_path(theatre) %></td>
        <td><%= link_to 'Destroy', theatre, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Theatre', new_theatre_path %>

bookingMovie/app/views/theatres/new.html.erb
<h1>New theatre</h1>

<%= render 'form' %>

<%= link_to 'Back', theatres_path %>

bookingMovie/app/views/theatres/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @theatre.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @theatre.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @theatre.state %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @theatre.zipcode %>
</p>

<%= link_to 'Edit', edit_theatre_path(@theatre) %> |
<%= link_to 'Back', theatres_path %>