bookingMovie/config/routes.rb
BookingMovie::Application.routes.draw do
  resources :users

  get "users/login"
  get "payments/make_a_payment"
  get "shopping_carts/add_to_cart"
  get "theatre_movies/theatre_movie_list" 
  resources :theatre_movies
  post "users/login"
  post "payments/make_a_payment"
  post "theatre_movies/theatre_movie_list"
  post "shopping_carts/add_to_cart"
  resources :payments

  resources :reviews

  resources :search_theatres

  get "search_theatres/search_theatre_byzip"
  post "search_theatres/search_theatre_byzip"
  resources :search_thatres

  resources :shopping_carts

  get "main_page/index"
  resources :movies

  resources :shows

  resources :screens

  resources :theatres

end

bookingMovie/app/models/shopping_cart.rb
class ShoppingCart < ActiveRecord::Base
	has_many :show
	has_one :payment
	has_one :user, through: :payment
end

bookingMovie/app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
  before_action :set_shopping_cart, only: [:show, :edit, :update, :destroy]
  $num_of_tickets = 0
  # GET /shopping_carts
  # GET /shopping_carts.json
  def index
    @shopping_carts = ShoppingCart.all
    @shows = Show.all
  end

  # GET /shopping_carts/1
  # GET /shopping_carts/1.json
  def show
    #binding pry
    @shopping_carts = ShoppingCart.find(params[:id])
    
  end

  # GET /shopping_carts/new
  def new
    @shopping_cart = ShoppingCart.new
  end

  # GET /shopping_carts/1/edit
  def edit
  end

  def add_to_cart
    $shows = Show.find(params[:show_id])
    $movies = Movie.find(params[:movie_id])
    $theatres = Theatre.find(params[:theatre_id])
    $num_of_tickets = params[:num_of_tickets]
  end

 

  # POST /shopping_carts
  # POST /shopping_carts.json
  def create
    
    #@shopping_cart = ShoppingCart.new(shopping_cart_params)
    @shopping_cart = ShoppingCart.new        
    @shows = Show.find(params[:show_id])
    #binding pry
    @shopping_cart.num_of_tickets = params[:num_of_tickets] 
    @shopping_cart.price_per_seat = 8.50 
    @shows.seats_avail = @shows.seats_avail - @shopping_cart.num_of_tickets
    if(@shows.seats_avail > 0)  
      respond_to do |format|
        if @shopping_cart.save
          format.html { redirect_to @shopping_cart}
          format.json { render action: 'show', :show_id => $shows.id, status: :created, location: @shopping_cart }
        else
          format.html { render action: 'new' }
          format.json { render json: @shopping_cart.errors, status: :unprocessable_entity }
        end
      end
    
    else
       @shows.seats_avail = @shows.seats_avail + @shopping_cart.num_of_tickets 
    end 
        
  end

  # PATCH/PUT /shopping_carts/1
  # PATCH/PUT /shopping_carts/1.json
  def update
    respond_to do |format|
      if @shopping_cart.update(shopping_cart_params)
        format.html { redirect_to @shopping_cart, notice: 'Shopping cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @shopping_cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shopping_carts/1
  # DELETE /shopping_carts/1.json
  def destroy
    @shopping_cart.destroy
    respond_to do |format|
      format.html { redirect_to shopping_carts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shopping_cart
      @shopping_cart = ShoppingCart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shopping_cart_params
      
      params.require(:shopping_cart).permit(:price_per_seat, :num_of_tickets)
    end
end

bookingMovie/app/helpers/shopping_carts_helper.rb
module ShoppingCartsHelper
end

bookingMovie/app/views/shopping_carts/_form.html.erb
<%= form_for(@shopping_cart) do |f| %>
  <% if @shopping_cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shopping_cart.errors.count, "error") %> prohibited this shopping_cart from being saved:</h2>

      <ul>
      <% @shopping_cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :num_of_tickets %><br>
    <%= f.number_field :num_of_tickets %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

bookingMovie/app/views/shopping_carts/add_to_cart.html.erb
<body class = "add_to_cart">
<img class = "image-border">
	<%=image_tag("horizontal-strip.jpg", alt: "Example Image")%>
	
</img>

<div class="left">
      <img class = "image-border-vertical">
        <%=image_tag("vertical-strip.jpg", alt: "Example Image")%>
      </img>
 </div>
 
 <h1>Book the Show</h1>
 <div class = "date">
 <b>Date of Show: <%= $shows.date_of_show.to_date.to_formatted_s(:long_ordinal) %></b><br>
 Time of the Show: <%= $shows.start_time.strftime("%H:%M") %>
</div>
<div class = "selected">
<%= form_tag({controller: "shopping_carts", action: "create"}, method: "post") do %>

    <%= label_tag(:adults) %>
    <%= select_tag (:num_of_tickets), options_for_select([['0', 0], ['1', 1], ['2', 2], ['3', 3], ['4', 4], ['5', 5], ['6', 6], ['7', 7], ['8', 8], ['9', 9], ['10', 10]]) %>&nbsp&nbsp&nbsp$8.50 per ticket<br><br>
    <%= label_tag (:children) %>
    <%= select_tag (:children), options_for_select([['0', 0],['1', 1], ['2', 2], ['3', 3], ['4', 4], ['5', 5], ['6', 6], ['7', 7], ['8', 8], ['9', 9], ['10', 10]]) %>&nbsp&nbsp&nbsp$5.50 per ticket<br><br>
    <%= label_tag (:seniors) %>
    <%= select_tag (:seniors), options_for_select([['0', 0],['1', 1], ['2', 2], ['3', 3], ['4', 4], ['5', 5], ['6', 6], ['7', 7], ['8', 8], ['9', 9], ['10', 10]]) %>&nbsp&nbsp&nbsp$6.50 per ticket<br><br>
    <div class= "hidden_tag">
    <%= select_tag (:show_id), options_for_select([['1', $shows.id]]) %><br>
    </div>
    <div class= "button">
    <%= button_to "Add to shopping cart" %>
    </div> 
    
<% end %>
</div>
</body>




  
   
   
   
         

 

bookingMovie/app/views/shopping_carts/edit.html.erb
<h1>Editing shopping_cart</h1>

<%= render 'form' %>

bookingMovie/app/views/shopping_carts/index.html.erb
<h1>Listing shopping_carts</h1>

<table>
  <thead>
    <tr>
      <th>Price per seat</th>
      <th>Num of tickets</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @shopping_carts.each do |shopping_cart| %>
      <tr>
        <td><%= shopping_cart.price_per_seat %></td>
        <td><%= shopping_cart.num_of_tickets %></td>
        <td><%= link_to 'Show', shopping_cart %></td>
        <td><%= link_to 'Edit', edit_shopping_cart_path(shopping_cart) %></td>
        <td><%= link_to 'Destroy', shopping_cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shopping cart', new_shopping_cart_path %>

bookingMovie/app/views/shopping_carts/new.html.erb
<h1>New shopping_cart</h1>

<%= render 'form' %>

<%= link_to 'Back', shopping_carts_path %>

bookingMovie/app/views/shopping_carts/show.html.erb
<body class = "add_to_cart">

<img class = "image-border">
	<%=image_tag("horizontal-strip.jpg", alt: "Example Image")%>
	
</img>

<div class="left">
      <img class = "image-border-vertical">
        <%=image_tag("vertical-strip.jpg", alt: "Example Image")%>
      </img>
 </div>
<%= form_tag({controller: "payments", action: "make_a_payment"}, method: "post") do %>

<h2><u>Booking Details</u></h2>

<p id="notice"><%= notice %></p>

<p><b>Theatre: <%= $theatres.name %></b></p>
<p>Address: <%= $theatres.city %>,&nbsp;<%= $theatres.state %>,&nbsp;<%= $theatres.zipcode %></p>
<p><b>Movie: <%= $movies.name %></b></p>

<p><b>Date of Show: <%= $shows.date_of_show.to_date.to_formatted_s(:long_ordinal) %></b></p>
 <p><b>Time of the Show: <%= $shows.start_time.strftime("%H:%M") %></b></p>

<p>
  <strong>Num of tickets:</strong>
  <%= @shopping_cart.num_of_tickets %>
</p>

<p>
  <strong>Total Amount Due:</strong>
 $ <%= @shopping_cart.price_per_seat*@shopping_cart.num_of_tickets %>
</p>
<div class = "edit">
<%= link_to 'Edit', edit_shopping_cart_path(@shopping_cart) %> <br>
</div>
<p><b>Check out as Guest</b></p>
<div class= "button_1">
<%= button_to "Make a Payment" %>
</div>
<% end %>

<p><b>User Login</b></p>

<div class= "button_1">
<%= button_to "User Login", controller: "users", action: "login", method: "post" %>
</div>

</body>